name: wave_desktop_installer
description: "Wave Window Installer"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  win_ble:
    path: packages/win_ble
  ota:
    path: packages/ota

  get_it: ^7.6.6
  rxdart: ^0.27.7
  freezed_annotation: ^2.4.1
  gap: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  freezed: ^2.4.5
  build_runner:

flutter:

  uses-material-design: true
