name: wave_desktop_installer
description: "Wave Window Installer"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  win_ble:
    path: packages/win_ble
  control_protocol:
    path: packages/control_protocol
  tcp_client:
    path: packages/tcp_client
  yaru:
    path: packages/yaru
  ftp_connect:
    path: packages/ftp_connect


  injectable: ^2.3.2
  get_it: ^7.6.6
  rxdart: ^0.27.7
  flutter_riverpod: ^2.5.1
  freezed_annotation: ^2.4.1
  json_serializable: ^6.7.1
  gap: ^3.0.1
  dio: ^5.4.3+1  # 클라이언트 http 요청 패키지
  pretty_dio_logger: ^1.3.1  # dio 로그 패키지
  retrofit: ^4.1.0  # dio 패키지를 사용한 http 요청 code generator 패키지
  easy_isolate_helper: ^1.0.0

  file: ^7.0.0
  path: ^1.9.0
  tuple: ^2.0.2


  cupertino_icons: ^1.0.6



  webview_windows: ^0.4.0
  window_manager: ^0.3.9
  percent_indicator: ^4.2.3
  animated_text_kit: ^4.2.2

  win32: ^5.5.1
  ffi: ^2.1.2
  expandable: ^5.0.1
  equatable: ^2.0.5
  collection: ^1.15.0

  flutter_localizations:  # 다국어 패키지
    sdk: flutter
  intl: any  # 포맷 패키지


dev_dependencies:
  flutter_test:
    sdk: flutter

  freezed: ^2.4.5
  injectable_generator:
  retrofit_generator:
  build_runner:
  flutter_gen_runner:
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/fonts/
  fonts:
    - family: NotoSansKR
      fonts:
        - asset: assets/fonts/NotoSansKR-Regular.ttf
          weight: 400
        - asset: assets/fonts/NotoSansKR-Bold.ttf
          weight: 700

flutter_gen:
  integrations:
    flutter_svg: true
  output: lib/assets/
