name: wave_desktop_installer
description: "Wave Window Installer"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  win_ble:
    path: packages/win_ble
  control_protocol:
    path: packages/control_protocol
  tcp_client:
    path: packages/tcp_client
  yaru:
    path: packages/yaru


  injectable: ^2.3.2
  get_it: ^7.6.6
  rxdart: ^0.27.7
  flutter_riverpod: ^2.5.1
  freezed_annotation: ^2.4.1
  gap: ^3.0.1
  dio: ^5.3.3  # 클라이언트 http 요청 패키지
  pretty_dio_logger: ^1.3.1  # dio 로그 패키지
  retrofit: ^4.0.3  # dio 패키지를 사용한 http 요청 code generator 패키지
  shared_preferences: ^2.2.2  # shared preferences 패키지

  file: ^7.0.0
  path: ^1.9.0


  cupertino_icons: ^1.0.6



  webview_windows: ^0.4.0
  window_manager: ^0.3.9
  percent_indicator: ^4.2.3

  win32: ^5.5.1
  ffi: ^2.1.2




dev_dependencies:
  flutter_test:
    sdk: flutter

  freezed: ^2.4.5
  injectable_generator:
  retrofit_generator:
  build_runner:
  flutter_gen_runner:
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/fonts/
  fonts:
    - family: NotoSansKR
      fonts:
        - asset: assets/fonts/NotoSansKR-Regular.ttf

flutter_gen:
  integrations:
    flutter_svg: true
  output: lib/assets/
