name: control_protocol
description: Protocol for controlling the device
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  equatable: ^2.0.5



dev_dependencies:
  fake_async: 1.3.1 
  mocktail: 1.0.0
  test: 1.24.4
  flutter_lints: ^3.0.0
