name: tcp_client
description: Tcp Client
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:

  control_protocol:
    path: ../control_protocol

  logging: ^1.2.0
  synchronized: ^3.1.0
  modbus_client: ^1.2.1





dev_dependencies:
  fake_async: 1.3.1
  mocktail: 1.0.0
  test: 1.24.4
  flutter_lints: ^3.0.0
