name: ftp_connect
description: Simple and robust dart FTP Connect Library to interact with FTP Servers.
version: 2.0.7

homepage: https://github.com/salim-lachdhaf
git: https://github.com/salim-lachdhaf/dartFTP
repository: https://github.com/salim-lachdhaf/dartFTP

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  path: ^1.9.0
  intl: ^0.19.0

dev_dependencies:
  test: ^1.25.2
  coverage: ^1.7.2
